[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/cli"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.8.2"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
